---
# tasks file for wso2db

- name: Ensure unzip is installed
  when: ansible_env.container is defined
  delegate_to: localhost
  run_once: true
  package:
    name: unzip
    state: present

- name: Ensure directory files/packs
  delegate_to: localhost
  connection: local
  run_once: true
  become: false
  file:
    path: "{{ product_package_location }}/packs/"
    state: directory
    mode: '0750'

- name: Download remote_pack into files/packs
  delegate_to: localhost
  connection: local
  run_once: true
  become: false
  get_url:
    url: "{{ remote_pack }}"
    dest: "{{ product_package_location }}/packs/{{ product_name }}-{{ product_version }}.zip"
    mode: u=rw,g=r,o=r

- name: Unzip WSO2 API Manager Package
  delegate_to: localhost
  connection: local
  run_once: true
  become: false
  unarchive:
    src: "{{ product_package_location }}/packs/{{ product_name }}-{{ product_version }}.zip"
    dest: "{{ product_package_location }}/packs/"
    creates: "{{ product_package_location }}/packs/{{ product_name }}-{{ product_version }}/LICENSE.txt"
    mode: u=rw,g=r,o=r
    remote_src: false
  no_log: false

- name: Run task for H2
  when: wso2am_db_type == 'h2'
  include_tasks: h2.yml

- name: Run task for MySQL
  when: wso2am_db_type == 'mysql'
  include_tasks: mysql.yml

- name: Run task for PostgreSQL
  when: wso2am_db_type == 'postgre'
  include_tasks: postgres.yml

...
